openapi: 3.0.3
info:
  title: variant monopoly CSR API
  version: 1.0.0
  description: 159356 Capstone Project
paths:
  /api/avatar/:
    get:
      operationId: api_avatar_list
      description: ''
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Avatar'
          description: ''
  /api/avatar/{id}/:
    get:
      operationId: api_avatar_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this profile.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Avatar'
          description: ''
    put:
      operationId: api_avatar_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this profile.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Avatar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Avatar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Avatar'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Avatar'
          description: ''
    patch:
      operationId: api_avatar_partial_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this profile.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAvatar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAvatar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAvatar'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Avatar'
          description: ''
  /api/login/:
    post:
      operationId: api_login_create
      description: ''
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '201':
          description: No response body
  /api/password/:
    get:
      operationId: api_password_list
      description: ''
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Password'
          description: ''
  /api/password/{id}/:
    get:
      operationId: api_password_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Password'
          description: ''
    put:
      operationId: api_password_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Password'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Password'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Password'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Password'
          description: ''
    patch:
      operationId: api_password_partial_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPassword'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Password'
          description: ''
  /api/register/:
    post:
      operationId: api_register_create
      description: ''
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateProfile'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProfile'
          description: ''
components:
  schemas:
    Avatar:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        avatar:
          type: string
          format: uri
          nullable: true
      required:
      - id
    CreateProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/User'
        avatar:
          type: string
          format: uri
          nullable: true
      required:
      - id
      - user
    Password:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - id
      - password
      - username
    PatchedAvatar:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        avatar:
          type: string
          format: uri
          nullable: true
    PatchedPassword:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        password:
          type: string
          writeOnly: true
          maxLength: 128
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - id
      - password
      - username
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
